enableTips: false

nodeLinker: node-modules

# Set YARN_NPM_AUTH_TOKEN in your shell before running publish commands.
npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
